steps:
- name: 'alpine'
  args: ['echo', '${_ENVIRONMENT}']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'env-production', '.env']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']